[project]
name = "avitotask"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.13.2",
    "pytest>=9.0.1",
    "pytest-asyncio>=1.3.0",
]
